/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 * Clase donde se crean los componentes graficos
 * @author Corin V
 */
public class ListarEstudiantes extends javax.swing.JFrame {

    /**
     * Constructor de la clase
     */
    public ListarEstudiantes() {
        initComponents();
        this.setVisible(true);
    }
    /**
     * Obtener el boton
     * @return boton
     */
    public JButton getB_registrar() {
        return b_registrar;
    }
    /**
     * Obtener el label del error
     * @return label
     */
    public JLabel getL_error() {
        return L_error;
    }
    /**
     * Obtener el Jtextfield donde ingresa los datos
     * @return JTextField
     */
    public JTextField getTb_nombres() {
        return tb_nombres;
    }
    /**
     * Obtiene el Jlist de los nombres
     * @return JList
     */

    public JList getL_nombres() {
        return jl_nombres;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_principal = new javax.swing.JPanel();
        l_nombre = new javax.swing.JLabel();
        tb_nombres = new javax.swing.JTextField(9);
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_nombres = new javax.swing.JList();
        b_registrar = new javax.swing.JButton();
        l_titulo = new javax.swing.JLabel();
        L_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));

        p_principal.setBackground(new java.awt.Color(188, 227, 235));

        l_nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_nombre.setText("Nombres");

        tb_nombres.setColumns(9);

        jl_nombres.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jl_nombres);

        b_registrar.setBackground(new java.awt.Color(102, 0, 0));
        b_registrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_registrar.setForeground(new java.awt.Color(255, 255, 255));
        b_registrar.setText("Registrar");

        l_titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_titulo.setForeground(new java.awt.Color(0, 51, 51));
        l_titulo.setText("LISTADO DE NOMBRES");

        L_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_error.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout p_principalLayout = new javax.swing.GroupLayout(p_principal);
        p_principal.setLayout(p_principalLayout);
        p_principalLayout.setHorizontalGroup(
            p_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_principalLayout.createSequentialGroup()
                .addGroup(p_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_principalLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(l_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(p_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_principalLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(l_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_principalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(p_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(p_principalLayout.createSequentialGroup()
                                        .addComponent(tb_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L_error))))))
                    .addGroup(p_principalLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(b_registrar)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        p_principalLayout.setVerticalGroup(
            p_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_principalLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(l_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(p_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_nombre)
                    .addComponent(L_error, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Añadir eventos tanto al boton como a la caja de texto
     * @param controler controlador de la vista
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_error;
    private javax.swing.JButton b_registrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jl_nombres;
    private javax.swing.JLabel l_nombre;
    private javax.swing.JLabel l_titulo;
    private javax.swing.JPanel p_principal;
    private javax.swing.JTextField tb_nombres;
    // End of variables declaration//GEN-END:variables
}
